name: spur
description: A new Flutter project.

version: 1.0.2+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  file_picker: ^8.0.5
  flutter_datetime_picker_plus: ^2.2.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  provider: ^6.1.2
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  rxdart: ^0.27.7
  upgrader: ^10.3.0
dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3

flutter_native_splash:
  color: "#007D69"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

# flutter pub run flutter_launcher_icons
# dart run flutter_native_splash:create
# dart run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true
  assets:
    - assets/images/
#  fonts:
#    - family: Ubuntu
#      fonts:
#        - asset: assets/cfg/400.ttf
#          weight: 400
#        - asset: assets/cfg/700.ttf
#          weight: 700
